### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by oofgangcrypin** [iBLiSSINonYT/survivio-plus#5]
It keeps freezing after 30 seconds, everything works fine except for that

**Comment by UnauthorisedEntity** [comment]
please work on this

**Comment by eliteog23** [comment]
Can you release the free version??

**Comment by eliteog23** [comment]
Like fr tho..

**Comment by humphreygaming** [comment]
nah, this is just iblissin being iblissin, not paying attention to his followers that he has been privileged to have and downright copying my friend IceHacks' code

**Comment by iBLiSSINonYT** [comment]
@humphreygaying

First, the solution was discussed in my videos as well on this Github.

Second, the followers came out of nowhere? Have you even searched up surviv.io hacks on Youtube?

Third, according to the code that I read, I can say it was definitely based off of this project, I change my opinion to 'I don't care' because the hack is open-source, my bad for calling IceHacks out.

Fourth, copying? Do you understand the concept of time? 

What exactly did I copy, if everything was made before he even STARTED to commit to Github?

Go check his page, there's the old copy. Read for yourself when any of these features were made. 

If anything, all of the common features were based off of my hack.

**Comment by humphreygaming** [comment]
and the ownership of the hack was given to you by malacus?

**Comment by oofgangcrypin** [comment]
I don’t see anything about the freezing
